apiVersion: v1
data:
  confa: exvalue
kind: ConfigMap
metadata:
  creationTimestamp: "2021-05-20T23:32:18Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:confa: {}
    manager: kubectl-create
    operation: Update
    time: "2021-05-20T23:32:18Z"
  name: my-config
  namespace: datatab
  resourceVersion: "97601"
  uid: 83f21df1-75ba-4821-b004-2ce991ef5052
